[tool.black]
line-length = 75
target-version = ['py38', 'py39', 'py310', "py311", "py312", "py313"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.venv
  | build
  | dist
  | venv
)/
'''