# Generated by Django 4.2 on 2025-05-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="catalog_doc",
            field=models.TextField(default="x", max_length=250),
        ),
        migrations.AlterField(
            model_name="services",
            name="catalog_file",
            field=models.TextField(default="x", max_length=250),
        ),
        migrations.AlterField(
            model_name="services",
            name="content",
            field=models.TextField(default="salam"),
        ),
        migrations.AlterField(
            model_name="services",
            name="description",
            field=models.TextField(default="text desc"),
        ),
        migrations.AlterField(
            model_name="services",
            name="specials",
            field=models.ManyToManyField(
                blank=True, null=True, to="services.special_services"
            ),
        ),
    ]
